### ISSUE TITLE
A better way to notify about parcels statuses

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/Paketin-Seuranta#1]
Hello,

I was looking at the source code, and there's some requests to your server for Finland Post. Can you make that open source, so we can improve things there? 

I was planning to add push notifications, because starting from Android 8.0, background threads are getting killed after a short time of running. Because of this, app's notifications aren't working.  :smile:

We can implement the server to push messages every x minute to check the parcels status. So the background threads will not be needed.

**Comment by norkator** [comment]
That "server" is actually straight towards posti own server. I don't forwards data on any way. I don't have server assosiated towards this app. So this is all source code for this whole app right here.

**Comment by norkator** [comment]
You can make new branch and add your developments there, I will review, test, merge and build done works.

**Comment by norkator** [comment]
I had long time ago problem that posti server ip was changing so I used my own domain service provider to stay up to date with their server. That problem no longer exists so I can change that to direct one.

**Comment by developerfromjokela** [comment]
Great! Then I can create a php script to push firebase push messages.

**Comment by norkator** [comment]
Where will this php script be located at? I don't allow any random servers due privacy issues

**Comment by developerfromjokela** [comment]
Hello, if you can, you can set it running on your server with cron. It will
push a FCM Push notification to the app, requesting to check for parcels
statuses, and bypassing the Android's "doze", which restricts running any
foreground services.

If you want, you can create a new repo for that server part.

**Comment by developerfromjokela** [comment]
@norkator Even if it's on my server, any user data will not be saved. All updates Will Be done on the user's device. Push update triggers the update. :wink:

**Comment by norkator** [comment]
Okay we'll see later when I review done works. Thanks for participating.

**Comment by developerfromjokela** [comment]
@norkator I made an separate repository for the server. https://github.com/developerfromjokela/Paketin-Seuranta-Server. You can fork it, to add more code if you want. This script will push an push message to the app, and the Firebase listener in the app is going to trigger the update.

**Comment by norkator** [comment]
Now that I see that you are very skilled so I think I stay out of this fire base notification development. I can set it later to run on my server but will only use directly your version so not going to do my own forks. I let you be specialist on this thing. Have to thank you again for participating.

So basically to enabled FCM I need to set up server key, set up script on my server with it but what about at Android app side, any requirements now there?

**Comment by norkator** [comment]
I double reviewed code because I don't understand this part "the Firebase listener in the app is going to trigger the update."  -> I haven't yet found this " Firebase listener " so how this works or is this yet to be implemented?

**Comment by developerfromjokela** [comment]
The app needs to have FCM listener service. It haven't been implemented yet.

**Comment by norkator** [comment]
I have server key now so I set up your fcm server code up and running on my server ready for this.

**Comment by norkator** [comment]
@developerfromjokela we have problem: https://github.com/norkator/Paketin-Seuranta/issues/5

maybe should drop support for Kitkat, what do you think? or should we try keep support. 

based on statistics only few people really have older Android version so obviously I will drop support.

**Comment by developerfromjokela** [comment]
Is there an dependency that doesn't support KitKat?

 I think we should stop the support when it's necessary, otherwise it's
great to keep supporting these old devices 😉.

Are there other reasons why you don't want to support KitKat? Let me know
😀.

**Comment by norkator** [comment]
I just dropped it. Released update.

**Comment by developerfromjokela** [comment]
Ok. When will you release the update to Google play?

**Comment by norkator** [comment]
> Ok. When will you release the update to Google play?

Its already in Googles processing

**Comment by developerfromjokela** [comment]
It's done, closing the issue
