### ISSUE TITLE
Nextgen branch

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#104]
@developerfromjokela can you give short intro to branch nextgen ideas?

**Comment by developerfromjokela** [comment]
I was planning to do a redesign, I'm currently little busy, so I'll go in-depth later this day.

**Comment by developerfromjokela** [comment]
So, I wanted to re-code the whole app as a new repository, and we can then merge that here.

Main problem for me has been notifications, I think if we make package checks on the server, we can save battery and CPU usage. (aka. Sending tracking code and checking for changes in server). Android comes with more restrictions as time passes, so on-device check becomes slowly unreliable.

**Comment by ristomatti** [comment]
> I think if we make package checks on the server, we can save battery and CPU usage

Which server are you talking about? I hope the plan is not to start checking/storing the states in an external server. I believe this might result in too many requests from a single point, enough to require using paid services.

How often are you checking for updates and how bug percentage of the battery tends to be used by the app while updating on the background?

**Comment by developerfromjokela** [comment]
The problem is not how often, it's simply not reliable, because Android limits background tasks to save battery automatically.

About the server, if designed correctly, it wouldn't be a expensive.
I don't think there's other reliable way for notifications, restrictions get more agressive over time.

**Comment by norkator** [comment]
> > I think if we make package checks on the server, we can save battery and CPU usage
> 
> Which server are you talking about? I hope the plan is not to start checking/storing the states in an external server. I believe this might result in too many requests from a single point, enough to require using paid services.
> 
> How often are you checking for updates and how bug percentage of the battery tends to be used by the app while updating on the background?

Theres other problems appearing too:
* Server will hit public parcel api's request limit so we need to start using paid apis. Who pays it?
* Who pays server and server from where?
* Privacy problems which was one original idea of this app to not request parcel details thru "creators" server.. I do however know people dont really give a s*** about this when comparing competitor apps which do like this.


@developerfromjokela Maybe should create fully new app having new approach with this app code as a base with support for global parcel tracking, new name, new logo new everything and make it full of paid content like others do. Also gather and sell information within limits of privacy laws.

**Comment by norkator** [comment]
Or just completely new app no connection to this app

**Comment by developerfromjokela** [comment]
Hmm, I see. Maybe I should launch a new app, so I could host the server (in Finland). I'm planning to keep it fully open source.

**Comment by developerfromjokela** [comment]
I understand the privacy issue for server, and I'll create a separate app. My primary issue is (and was) notifications. maybe I should reinvent the server part to preserve privacy as much as possible.

**Comment by norkator** [comment]
> I understand the privacy issue for server, and I'll create a separate app. My primary issue is (and was) notifications. maybe I should reinvent the server part to preserve privacy as much as possible.

Sounds good and to make competitor to parcels app.

**Comment by norkator** [comment]
@developerfromjokela anyway I like the idea and your plan is right way to do it!

**Comment by ristomatti** [comment]
Just watch out for GDPR stuff if you're planning on doing the checks on the server and pushing notifications based on that.

Parcels app is quite crappy IMO but their mobile web search at parcelsapp.com is quite amazing. It will save all previous searches to local storage and you can even replace the tracking code with a memorable name. If I'd only need simple tracking without additional info/archiving/exporting I might just use the web app.

**Comment by developerfromjokela** [comment]
Yes, the app isn't the best and it has an issue of leaking tracking codes (informed to developer, no response for over a year), so.

**Comment by norkator** [comment]
> Yes, the app isn't the best and it has an issue of leaking tracking codes (informed to developer, no response for over a year), so.

"leaking tracking codes" sounds like a feature

**Comment by norkator** [comment]
I assume this conversation is finished

**Comment by developerfromjokela** [comment]
I would like to give a small update.
So I've started working on a new app (open-source), new and fresh codebase. I plan to make notifications work without server side processing, until it is really mandatory, and I'll keep that as an optional feature, not activated by default.

Here's a screenshot:
![Screenshot_20210422-231452.png](https://user-images.githubusercontent.com/40487414/115779782-1027ee00-a3c1-11eb-923f-75d94595c1c9.png)

App isn't near to its completion yet, but we can possibly merge our efforts some day 😊

**Comment by norkator** [comment]
> I would like to give a small update.
> So I've started working on a new app (open-source), new and fresh codebase. I plan to make notifications work without server side processing, until it is really mandatory, and I'll keep that as an optional feature, not activated by default.
> 
> Here's a screenshot:
> ![Screenshot_20210422-231452.png](https://user-images.githubusercontent.com/40487414/115779782-1027ee00-a3c1-11eb-923f-75d94595c1c9.png)
> 
> App isn't near to its completion yet, but we can possibly merge our efforts some day 😊

I dont know can I bring much value for your version. Should you just release it when ready as a totally new app, I assume you target it for global tracking and not only Finland like I do here.

**Comment by norkator** [comment]
Anyway lets talk about it when you get closer to first release.

**Comment by developerfromjokela** [comment]
> > I would like to give a small update.
> > So I've started working on a new app (open-source), new and fresh codebase. I plan to make notifications work without server side processing, until it is really mandatory, and I'll keep that as an optional feature, not activated by default.
> > Here's a screenshot:
> > ![Screenshot_20210422-231452.png](https://user-images.githubusercontent.com/40487414/115779782-1027ee00-a3c1-11eb-923f-75d94595c1c9.png)
> > App isn't near to its completion yet, but we can possibly merge our efforts some day blush
> 
> I dont know can I bring much value for your version. Should you just release it when ready as a totally new app, I assume you target it for global tracking and not only Finland like I do here.

I am planning to target Finland, because global targeting is too huge, there are too many couriers to support :smile:

**Comment by norkator** [comment]
> > > I would like to give a small update.
> > > So I've started working on a new app (open-source), new and fresh codebase. I plan to make notifications work without server side processing, until it is really mandatory, and I'll keep that as an optional feature, not activated by default.
> > > Here's a screenshot:
> > > ![Screenshot_20210422-231452.png](https://user-images.githubusercontent.com/40487414/115779782-1027ee00-a3c1-11eb-923f-75d94595c1c9.png)
> > > App isn't near to its completion yet, but we can possibly merge our efforts some day blush
> > 
> > 
> > I dont know can I bring much value for your version. Should you just release it when ready as a totally new app, I assume you target it for global tracking and not only Finland like I do here.
> 
> I am planning to target Finland, because global targeting is too huge, there are too many couriers to support 😄

Will you try to put time on visuals to make it different or like posti app is?
