### ISSUE TITLE
Paid / Unpaid field

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#105]
> Oikein näppärä sovellus. Kehitysehdotus: voisi lisätä kentän maksun tila maksettu/ei maksettu. Näin näkee heti mikä tilaus pitäisi vielä maksaa

Asked more details what kind lf idea in mind to be specific

**Comment by norkator** [comment]
> Tämän voisi lisätä sieltä kynän kuvasta ja olisi tosi kätevää jos tulisi eri ikoni sitten näkyviin seurantatiedoissa, joku pieni ikoni vsikka kokoa kuljetusyhtiö.

**Comment by ristomatti** [comment]
I would believe in >95% of cases the tracked thing is already paid. I'd suggest displaying the icon should be an opt-in feature if added, like the courier icon is now.

**Comment by ristomatti** [comment]
If done this should also be displayed in the detail view and included in the export feature data.

**Comment by norkator** [comment]
> I would believe in >95% of cases the tracked thing is already paid. I'd suggest displaying the icon should be an opt-in feature if added, like the courier icon is now.

Yes I have branch, doing this already and yes by default its off, its just boolean toggle when adding/editing parcel

**Comment by norkator** [comment]
I will test one kind of implementation suitable for this person needs without affecting others.
