### ISSUE TITLE
An issue with backup

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/paketin-seuranta#107]
When exporting the file, it should be at Android/data/<packagename>. This works well until Android 11, when data folder becomes unaccessible by user. So in Android 11 you cannot navigate to Android/data via file explorer.

**Comment by norkator** [comment]
😠  Google what..

**Comment by norkator** [comment]
Why data folder became unaccessible, just noticed this too with my phone having now Android 11

I wonder is there any dependency file manager / utils which has logic to handle new permissions, creating folders and moving files.

**Comment by norkator** [comment]
So that could outsource this problem

**Comment by developerfromjokela** [comment]
You could put a share button to share that backup file via intent

**Comment by ristomatti** [comment]
OT: I think this was a frustrating change. Another thing that came was preventing some sort of code execution within an app. I for example use Termux to get access to a bunch of Linux terminal utils locally but IIRC they haven't yet figured out how to support Android 11. Same likely applies to all the "install Linux inside Android" apps I'm guessing.

Better security, less freedom for hacking. 🙁

**Comment by norkator** [comment]
> You could put a share button to share that backup file via intent

Didnt even think of this. Not bad idea!
