### ISSUE TITLE
Cainiao Parcel marked as invalid, if destCountry is null

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/Paketin-Seuranta#11]
There is an issue with the Cainiao parcels, if destination country is for some reason null, it marks it as invalid package, when the API reports back parcel's details. Cainiao's API gives back a success boolean, I think it's better to use that instead.

**Comment by developerfromjokela** [comment]
There was an issue with the Cainiao API. It didn't fetch anything giving an error. I've found another way to retrieve details.

**Comment by norkator** [comment]
I close this due pull request, pull request contents are released on Google Play moment ago.
