### ISSUE TITLE
Need to find maintainers

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#112]
This project really needs some maintainers to keep things working in the future when implementations just break more and more. I badly lack time to spent to this project.

**Comment by ristomatti** [comment]
Next time a courier breaks and you're not needing for your own purposes, I would say just disable the particular courier (in a way that it won't break packages which already have it set of course).

**Comment by norkator** [comment]
> Next time a courier breaks and you're not needing it for your own purposes, I would say just disable the particular courier (in a way that it won't break packages which already have it set of course).

Do you still use this app yourself?

I still use so I will try keep tracking working but wont be checking them time to time but only when coming across broken one like today.

**Comment by ristomatti** [comment]
Yup still using pretty much daily! Recently most packages have been tracked either with Posti or Cainiao so haven't had the chance to try others. UPS/DHL every now and then.

**Comment by norkator** [comment]
Closing. I keep maintaining this myself anyway. Customs handling needs are just increasing my need to develop this app further.
