### ISSUE TITLE
User interface improvements

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#124]
Any ideas to make this app user interface somehow sweeter. Not hyper over materialised like some apps but something sweet?

Maybe @Maiska123 would have some ideas? throw anything!

**Comment by ristomatti** [comment]
We could start by thinkng of apps with approximately similar interface that we've used and liked?

**Comment by norkator** [comment]
I am open for ideas, throw anything @ristomatti @Maiska123

**Comment by norkator** [comment]
Closing because inactive.
