### ISSUE TITLE
Push Message interval

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/Paketin-Seuranta#13]
Hello,

I've set my update interval to 0, which matches the server's cron job.

How is the cron set up? What's the interval there? 5 minutes?

**Comment by norkator** [comment]
30 minutes at the moment, do you want lower?

**Comment by developerfromjokela** [comment]
Well yes I was thinking it was on 5 minutes, is it possible / ok to set it to 5 minutes? 
What do you think?
I personally would like to receive updates every 5 minutes. 
Fortunately this is configurable in settings for every user. :wink:

**Comment by norkator** [comment]
5 min in use

**Comment by developerfromjokela** [comment]
Ok thanks
