### ISSUE TITLE
Feature request: filter duplicate tracking codes from barcode list

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#156]
I've now created two orders from AliExpress using their new "combined delivery" option. Initially I thought it only meant that the packages will only be shipped in the same container as all the bundled orders were created separately with a distinct tracking code for each. These tracking codes were even found via Cainiao tracking.

Yesterday while investigating why the tracking status on most of my incoming parcels had not changed for several days, I noticed the tracking information had been updated. Now all the combined orders have the same trackng code. Luckily it's possible to use existing tracking codes when editing a parcel in Paketin Seuranta. Now when the time comes to pick the packages, I'm expecting the barcodes to show up multiple times which would be inconvenient :grimacing:.

I've verified from `BarcodeList.java` that duplicates aren't checked. An ugly hack like this would probably do the trick (although against all my coding priciples :joy:):
```java
    private void getParameters(final Boolean readyToPickUpOnly) {
        ArrayList<String> parcelCodeItems = new ArrayList<>();
        ArrayList<String> parcelTitleItems = new ArrayList<>();
        Cursor res = null;
        if (readyToPickUpOnly) {
            res = databaseHelper.getAllDataWhereReadyToPickupState();
        } else {
            res = databaseHelper.getAllData();
        }
        while (res.moveToNext()) {
            String code = res.getString(3);
            // Skip duplicate codes
            if (!parcelCodeItems.contains(code)) {
                parcelCodeItems.add(res.getString(3));
                parcelTitleItems.add(res.getString(31));
            }
        }
```
I could see someone get confused with this though if they've accidentally added the same code for two parcels :thinking:. But still it feels silly to add a setting for this. What do you think?

**Comment by norkator** [comment]
I take a look about this, this week later.

**Comment by norkator** [comment]
> Luckily it's possible to use existing tracking codes when editing a parcel in Paketin Seuranta.
So you used this bug to add same parcel code two times => I forgot this was possible but seems handy so not gonna fix it.

..but you want that barcode listing only shows one of them?
