### ISSUE TITLE
Bring tracking implementation

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#16]
This is requested by user

https://tracking.bring.com/tracking/api/fetch/1234567898?lang=en

Content-Type: application/json

Response with bad code: {"errorId":"4825866b-9c9e-4f05-a82b-0e4d5c8fa70f","errorCode":"2404","errorMessage":"Unable to locate 1234567898"}

Need to get working tracking number before implementation attempt

**Comment by developerfromjokela** [comment]
Here's one: `TESTPACKAGE-AT-PICKUPPOINT`

**Comment by developerfromjokela** [comment]
Found in Bring API Documentation: [https://developer.bring.com/api/tracking/](https://developer.bring.com/api/tracking/)

**Comment by developerfromjokela** [comment]
Bring API is somewhat logical. I think it's easy to build the client part for it

**Comment by developerfromjokela** [comment]
Bring API Documentation has some example responses: [https://developer.bring.com/api/tracking/#tracking-endpoint-response-200](https://developer.bring.com/api/tracking/#tracking-endpoint-response-200)

**Comment by norkator** [comment]
There is now pull request waiting for review @developerfromjokela
