### ISSUE TITLE
GPLv3 License violation (readme)

### ISSUE THREAD

**Issue by raikasdev** [norkator/paketin-seuranta#167]
Same thing as in the other repo, you say in readme:
`You are not allowed to copy or use this app code to create similar application to distribute it on Google Play or any other store.`
while the GPLv3 license allows this completely, but requires the other app to release it's own source code if it is distributed (as it is a copyleft).

**Comment by norkator** [comment]
> Same thing as in the other repo, you say in readme: `You are not allowed to copy or use this app code to create similar application to distribute it on Google Play or any other store.` while the GPLv3 license allows this completely, but requires the other app to release it's own source code if it is distributed (as it is a copyleft).

So same case here as you said in other repo to maybe use this https://commonsclause.com/

**Comment by norkator** [comment]
@ristomatti do you want to give your opinion to this? (original story here https://github.com/norkator/open-intelligence/issues/191, how this got started)

**Comment by ristomatti** [comment]
@raikasdev BTW this repo you've contributed to https://github.com/Testausserveri/TestausFood is also suffering from a similar issue. It says the code is FOSS but since there's no explicit license, AFAIK this prevents using it as such. :slightly_smiling_face:
