### ISSUE TITLE
Posti integration is broken

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#194]
Reported by user.

**Comment by developerfromjokela** [comment]
Posti API has been changed to graphql.

Try to intercept traffic in browser and have a look at it yourself.

**Comment by norkator** [comment]
Yes just after opening issued checked out this

`https://oma.posti.fi/graphql/v2`
some work probably to figure out `authorization: Bearer` and such.

I check this some weekend unless someone else does it first.

**Comment by developerfromjokela** [comment]
Bearer comes from a request. It's not an actual authentication, posti's API
is just stupidly made.

I will send some documentation today evening.

**Comment by norkator** [comment]
Like here `https://auth-service.posti.fi/api/v1/anonymous_token`?

anyways, thanks!
