### ISSUE TITLE
DHL Express tracking fails

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#207]
I've got an Express package on the way which should have tracking info. I've sent you the code via the usual channel. 🙂

Aside: I've been on a bit of a shopping spree for the summer. Based on that I can confirm UPS, Posti, Matkahuolto and Cainiao tracking still work. 😁 

I also made a curious observation: I received this tracking code from the sender of the DHL package 00340434287098544863. It turned out to be some other somehow related code, but before I realized this, I ran the find courier search using it. Cainiao tracking gives a match but the tracking status is [CN]STOPCRAWLER. 😄

**Comment by norkator** [comment]
It does something else to that bm_sz cookie token before it can really be used. Authorizes it or something.

**Comment by norkator** [comment]
okay theres one more step doing some verify call with `bm_sz` and more important `sec_cpt` to clearly authorize `bm_sz` token. Need to figure this out.

**Comment by ristomatti** [comment]
Is a purely scraper based technique out of the question in this case? With something like https://github.com/skrapeit/skrape.it?

**Comment by norkator** [comment]
feels too overkill for this

**Comment by ristomatti** [comment]
Yep surely if it can be worked around with a reasonable effort. Lib like that would likely bloat the app size quite a lot but then again could save a ton of development time. But I guess you like puzzles like this. :sunglasses:

**Comment by ristomatti** [comment]
It's a bit peculiar to what lengths these businesses go to stop people from tracking packages sent by themselves.

**Comment by ristomatti** [comment]
Have you considered if it could be done via some other tracking service :grimacing:?

**Comment by norkator** [comment]
> some other tracking service

then tracking details would go trough someone else again. I would like to see this using direct courier services in the future just like now.

**Comment by ristomatti** [comment]
Good point.

**Comment by norkator** [comment]
I decided to create account and get api key. It has 250 daily call limit but it can be requested as higher. If it has price tag then "deal with it"

**Comment by norkator** [comment]
![Screenshot 2022-06-19 at 19 38 17](https://user-images.githubusercontent.com/55850510/174491331-8eb7a81c-09de-4a42-8a65-04bdc53f3348.png)

heres form to request higher call limit
