### ISSUE TITLE
Bug: Clicking add, then closing app, and there appears an "corrupted-like" package

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/paketin-seuranta#26]
So if you click add and don't fill anything just exit the hard way "force close", in database appears to be inserted blank package with empty details.

Is it possible to somehow not to add the package when opening add window? Wouldn't it be better way?

**Comment by norkator** [comment]
I need to look this since I made this behavior on some real "reason" maybe didn't know back then hoe to solve. I remember having some issues if I didnt pre insert empty line beforehand.
