### ISSUE TITLE
Backup is broken on Android 10

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#27]
The storage permission system/API's changed on Android 10. Since my phone upgraded to it I haven't been able to do backups.

Error I'm getting says "Varmuuskopion otto epäonnistui. Tämä tapahtuu joskus kun sovellus ei ilmeisesti ehdi luomaan kansiota. Yritä uudelleen niin toiminnon pitäisi onnistua." However retrying does not help. I believe the permission would need to be requested in place and the file storage probably done using some new API.

**Comment by norkator** [comment]
I may look this tomorrow late
