### ISSUE TITLE
Posti re-routing state handling

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#31]
![image](https://user-images.githubusercontent.com/55850510/89679896-a3d09180-d8fa-11ea-9d7b-3150816e7f99.png)

We may not have yet handling for this state. Also we don't know it's phase. Taking this up here.

**Comment by developerfromjokela** [comment]
Is this screenshot from another user? Or is it your package?

And is there something in posti's documentation?

**Comment by norkator** [comment]
> Is this screenshot from another user? Or is it your package?
> 
> And is there something in posti's documentation?

Its from user and old stuff from Trello. I couldn't catch it's phase name at that time.

**Comment by norkator** [comment]
I try see if AfterShip has some test package going into suitable state with this one.

**Comment by norkator** [comment]
I close this for now. Lets see later if we need to check this again.
