### ISSUE TITLE
Improvement: Maybe we should switch from ListView to RecyclerView?

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/paketin-seuranta#41]
ListView is now old, Google itself recommends using RecyclerView. 

I've seen in the app when I archive something, the courier Icon spacing gets messed up. I suspect that to the ListView.

Also if my list is able to scroll down, when trying to scroll up, swipe-to-refresh always hits me.

**Comment by norkator** [comment]
> ListView is now old, Google itself recommends using RecyclerView.
> 
> I've seen in the app when I archive something, the courier Icon spacing gets messed up. I suspect that to the ListView.
> 
> Also if my list is able to scroll dowb, when trying to scroll up, swipe-to-refresh always hits me.

That is true and I fully approve changing to recyclerview!

**Comment by developerfromjokela** [comment]
@norkator in the latest update, swipe refresh no longer works. Is it intended to be like that?

**Comment by developerfromjokela** [comment]
It works when I launch the app, if I scroll down, and scroll back up to pull it down, it no longer works

**Comment by norkator** [comment]
> It works when I launch the app, if I scroll down, and scroll back up to pull it down, it no longer works

I cannot re produce, works on my devices.

**Comment by developerfromjokela** [comment]
Hmm interesting, I am using Android 10 on Pixel 4 XL.

You enter the app, immediately after you scroll down, I think the Swipe to refresh gets disabled.

When I scroll back up, it never gets enabled.

**Comment by norkator** [comment]
> Hmm interesting, I am using Android 10 on Pixel 4 XL.
> 
> You enter the app, immediately after you scroll down, I think the Swipe to refresh gets disabled.
> 
> When I scroll back up, it never gets enabled.

Okay yes Android 10 has problems with it.

**Comment by norkator** [comment]
> Hmm interesting, I am using Android 10 on Pixel 4 XL.
> 
> You enter the app, immediately after you scroll down, I think the Swipe to refresh gets disabled.
> 
> When I scroll back up, it never gets enabled.

After more testing looks like onScroll with firstVisiblePosition works when looking from logs but
swipeRefreshLayout.setEnabled does not set it's state everytime. Something wrong with swipeRefreshLayout

**Comment by norkator** [comment]
Yep, on api 28 it works first okay and suddenly stops working all together.

**Comment by developerfromjokela** [comment]
@norkator Is the update released to fix the Swipe refresh problem?

**Comment by norkator** [comment]
> @norkator Is the update released to fix the Swipe refresh problem?

Yes.

**Comment by developerfromjokela** [comment]
@norkator On my device problem still exists

**Comment by norkator** [comment]
> @norkator On my device problem still exists

What device you have? Is it possible that play store cache caused esrlier version as update? What does version code say at about view?

**Comment by developerfromjokela** [comment]
@norkator Pixel 4 XL, version code 128 version name 2.1.11

**Comment by norkator** [comment]
> @norkator Pixel 4 XL, version code 128 version name 2.1.11

I am using Android 10 phone now too but it works for me. What kind of behavior it does for you?

**Comment by ristomatti** [comment]
I was able to reproduce it now also. This time it requires first opening package details, scrolling it down, pressing back. After returning to list view pull to refresh doesn't necessarily trigger straight after scrolling up but it triggers before the topmost item is fully visible.

**Comment by norkator** [comment]
> I was able to reproduce it now also. This time it requires first opening package details, scrolling it down, pressing back. After returning to list view pull to refresh doesn't necessarily trigger straight after scrolling up but it triggers before the topmost item is fully visible.

Aaa. Onresume, onpause event or any other has been rogotten maybe for checking.

**Comment by norkator** [comment]
> I was able to reproduce it now also. This time it requires first opening package details, scrolling it down, pressing back. After returning to list view pull to refresh doesn't necessarily trigger straight after scrolling up but it triggers before the topmost item is fully visible.

Update, tried too.. yes topmost item is not fully visible till refresh triggers. This is now tricky because listview position gives 0 already. 👎

**Comment by developerfromjokela** [comment]
@norkator Just checked out, issue happens while it's refreshing. When refreshing stops, it works like it should.

**Comment by norkator** [comment]
Okay I found problem.. listview should be inside swipe refresh layout but it was not. All those code change were total "hacks" so removed them.

**Comment by norkator** [comment]
See https://github.com/norkator/paketin-seuranta/pull/68

**Comment by norkator** [comment]
I start working on recycler view at least initially for main menu. Targeting to make it more nicer looking.
