### ISSUE TITLE
Having no ads or in app boughts affect on visibility

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#43]
I have feeling around Google Play that apps having no google ads or in app boughts wont be pushed by google as hard as ones having them.

Same happens with youtube videos.

Should we have even in app donate button?

**Comment by norkator** [comment]
No ads is a must but I will research this subject.

**Comment by ristomatti** [comment]
Reopened this. I tried donating but after approving the payment, I for a "transaction denied" error.

**Comment by norkator** [comment]
> Reopened this. I tried donating but after approving the payment, I got a "Transaction was declined" message.

I tested donation and it works. Rhat denied may be something not related to my side, credit card with valid details?

**Comment by norkator** [comment]
> > Reopened this. I tried donating but after approving the payment, I got a "Transaction was declined" message.
> 
> I tested donation and it works. That denied may be something not related to my side, credit card with valid details?

Oh for fuck sake, google has frozed my account, that is the problem case here. I know reason but cannot do much due corona affecting their ticket solving speed.

**Comment by ristomatti** [comment]
Ping me when they resolve it. I'll then verify it by donating and close the issue if it works. 🙂

**Comment by norkator** [comment]
> Ping me when they resolve it. I'll then verify it by donating and close the issue if it works. 🙂

😭 Terrible loss of money happening all the time

**Comment by norkator** [comment]
Still in progress. More info at monday.

**Comment by norkator** [comment]
@ristomatti got email from Google, they have now approved my account to continue selling in app products.

**Comment by norkator** [comment]
Closing, problem should be now gone.

**Comment by ristomatti** [comment]
> Closing, problem should be now gone.

Confirmed. Treat yourself with a cup of coffee. ☕

**Comment by norkator** [comment]
> > Closing, problem should be now gone.
> 
> Confirmed. Treat yourself with a cup of coffee. ☕

:D Google is taking part of my coffee.

**Comment by norkator** [comment]
> > Closing, problem should be now gone.
> 
> Confirmed. Treat yourself with a cup of coffee. ☕

![image](https://user-images.githubusercontent.com/55850510/90506961-bf8b3180-e15d-11ea-8c9d-60babc8542df.png)

then 30% tax from 1.41 euros -> 1.08 -> I buy coffee which has more tax -> throw up.

**Comment by ristomatti** [comment]
I tried to donate again to make it a full coffee cup but the first two times I tapped "donate" nothing happened. Then I pressed home, switched back to the app and tried again - app force closed. Reopened, tapped donate, same thing. I don't know if donating several times should be possible but if it should it looks like there's a bug...

**Comment by norkator** [comment]
> I tried to donate again to make it a full coffee cup but the first two times I tapped "donate" nothing happened. Then I pressed home, switched back to the app and tried again - app force closed. Reopened, tapped donate, same thing. I don't know if donating several times should be possible but if it should it looks like there's a bug...

Long time ago I implemented this billing fast to other apps, just created one time product so you can buy it only once. Maybe some day I take more time to improve and add something to tell that it's bought already. That app force close is good find, billing client died. So yes it's a bug and same time my way of working ⚰️

**Comment by ristomatti** [comment]
Ah that makes sense. But as they say: better fail fast (than to add too much null checks or catch blocks that will hide an unexpected issue).

**Comment by ristomatti** [comment]
Maybe you should raise the donation sum enough to result an actual 2.5€. At least if there's not many people donating, then it might backfire.

**Comment by norkator** [comment]
> Ah that makes sense. But as they say: better fail fast (than to add too much null checks or catch blocks that will hide an unexpected issue).

Just today morning I had problem with other app billing and had to add more handling for billing results, should bring those here because now theres no handling for that already bought event or cancellation etc.

**Comment by norkator** [comment]
> Maybe you should raise the donation sum enough to result an actual 2.5€. At least if there's not many people donating, then it might backfire.

Yes I can raise it. Mainly idea to have billing was to get that info to google play and now monitor/test does it affect google's side to tell about this app to people.
