### ISSUE TITLE
Fix manual language change feature

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#47]
"Nyt uusimman päivityksen jälkeen sovelluksen kielen vaihto ei toimi enää ollenkaan. Aluksi kieli näkyy oikein, mutta heti kun sovelluksessa klikkaa jotakin muuttuu kieli suomeksi." <-- Android 10, device lang Finnish but overrided to English from app settings. Won't work. This implementation seems to be breaking on every new Android so better remove this and do as Google wants, meaning always follow device language. I find this causing non wanted work.

**Comment by norkator** [comment]
This is good first issue for somebody wanting to contribute 😸

**Comment by developerfromjokela** [comment]
I've seen this also in my own apps.

In one app I solved it by adding something, but that stopped that theme by system default working. Theme won't follow the system until app restarts.

**Comment by ristomatti** [comment]
Damn Android 10. I didn't remember noticing any change meaningful to me but a lot of things breaking. I understand some of the changed were security related but.. Meh.

**Comment by norkator** [comment]
So this problem started again when I upgraded androidx.appcompat:appcompat to newest version 1.2.0.. not going to downgrade.
