### ISSUE TITLE
Issues with an empty package

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#48]
After adding a new package for tracking an empty package had appeared above it. It might have something to do with the fact I had the phone screen off for quite some time before realising I forgot to save it(?) 

I then I noticed packages cannot be removed from the list anymore. It didn't seem to matter if it was the empty package that appeared by itself or some another another one with some fields filled in.

**Comment by developerfromjokela** [comment]
Issue #26 already open for this bug

**Comment by ristomatti** [comment]
> Issue #26 already open for this bug

Thanks! I had missed it but the broken remove feature wasn't mentioned so let's still keep this open (unless I missed it being discussed also).

**Comment by ristomatti** [comment]
@norkator Any update when this will be pushed an update? The empty packages I cannot remove are quite annoying. 😄
