### ISSUE TITLE
Yanwen tracking broken again? 

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#66]
Tracking code VR344217874YP can be found from Yanwen's own tracking (and also ParcelsApp tracking finds it) but PS doesn't detect the courier and is unable to fetch any details if Yanwen is manually selected.

**Comment by norkator** [comment]
Interesting. I find it from Cainiao https://global.cainiao.com/detail.htm?mailNoList=VR344217874YP as well is finding PS

**Comment by ristomatti** [comment]
Yep found it through Cainiao also but not using Yanwen although I found it from Yanwen's own web tracking.
