### ISSUE TITLE
Pull to refresh too eager after using sideways swipe

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#67]
Pull to refresh does no more trigger when just scrolling up, so that is fixed. For some reason the same problem resurfaces if I swipe a parcel on the list first. It doesn't even need to complete any action, just peek "delete package" action a bit and then scroll up.

Android 10 yet again.

**Comment by norkator** [comment]
I feel like this is exactly what I found here: https://github.com/norkator/paketin-seuranta/pull/61

Update is released but waiting it to land at store.

**Comment by ristomatti** [comment]
Great! I thought it was about fixing the previous issue.

**Comment by norkator** [comment]
> Great! I thought it was about fixing the previous issue.

Well lets see after update do you still have this problem. Lets keep this open.

**Comment by norkator** [comment]
Update is available, just downloaded it.

**Comment by ristomatti** [comment]
Cannot reproduce with the new version. Closing.

**Comment by norkator** [comment]
Yay!!!! 👍
