### ISSUE TITLE
Testing and new release

### ISSUE THREAD

**Issue by norkator** [norkator/Paketin-Seuranta#7]
- What happens if push notification kicked update is run if no packages on list, ignored?
- What else?

Make release if testing shows green light.

**Comment by developerfromjokela** [comment]
If the list is empty, what would the update do? Doesn't it just do nothing like without the push notification? How did the updater act before?

**Comment by norkator** [comment]
I never saw automatic updates really working at all. Your implemented fcm is gold so I just want to test different scenarios, will comment on weekend results.

**Comment by developerfromjokela** [comment]
If you'll make a debuggable APK with the push notification, I can test it also.

**Comment by norkator** [comment]
Released new update!

**Comment by developerfromjokela** [comment]
Great! Looking forward to the update, when it will get published.
