### ISSUE TITLE
DHL Express notifying same change all over again every time

### ISSUE THREAD

**Issue by developerfromjokela** [norkator/paketin-seuranta#84]
DHL express update notification is broken, it notifies same change again and again. Gets little annoying.

**Comment by norkator** [comment]
I try check this soon too so that fix would be implemented in next update

**Comment by norkator** [comment]
Test code: 9247527586

**Comment by norkator** [comment]
If notification comes basically all the time after every update event then data must have some change:
- Only data changing every api call time seems to be "signature" lin url and it's id but that is not being used for comparing before showing notification.

I will do tests with test package at physical phone to see more.
