### ISSUE TITLE
Android app bundle part two

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#94]
Now app is ready for aab (Android App Bundle) with Jenkins run builds but still need to see how new release works with it. Already tried uploading release bundle and it was uploaded without problems (signing works). Releasing it and does it ship to users properly is question mark.

**Comment by ristomatti** [comment]
I guess there's only one way to find out? 🙂

**Comment by norkator** [comment]
> I guess there's only one way to find out? 🙂

Yes but want to have actual updates too 😄

**Comment by norkator** [comment]
Testing now actual releasing with another app having now same process
